baseURL = 'https://example.org/'
title = 'FMFI návody'
theme = 'matfyz'
defaultContentLanguage = 'sk'
defaultContentLanguageInSubdir = true

[languages]
  [languages.sk]
    label = 'Slovenčina'
    locale = 'sk'
    weight = 1
    title = 'FMFI návody'

  [languages.en]
    label = 'English'
    locale = 'en'
    weight = 2
    title = 'FMFI Guides'

  [languages.uk]
    label = 'Українська'
    locale = 'uk'
    weight = 3
    title = 'FMFI Посібники'

[params]
  menuDepth = 3
