baseURL = 'https://example.org/'
title = 'FMFI návody'
theme = 'matfyz'
defaultContentLanguage = 'sk'
defaultContentLanguageInSubdir = true
enableGitInfo = true

[languages]
  [languages.sk]
    label = 'SK'
    locale = 'sk'
    weight = 1
    title = 'FMFI návody'

  [languages.en]
    label = 'EN'
    locale = 'en'
    weight = 2
    title = 'FMFI Guides'

  [languages.uk]
    label = 'UA'
    locale = 'uk'
    weight = 3
    title = 'FMFI Посібники'


[params]
  menuDepth = 3
